### ISSUE TITLE
Weather app icon size reduced

### ISSUE THREAD

**Issue by dimaamid** [rllbe/weatherdate#1]
The weather app icon theming reduces the size of the weather app icon compared to normal app icons 
![44E92482-B2BD-4613-B9DC-E605FA1CF80C](https://user-images.githubusercontent.com/1293540/126572120-fc8a175a-44fd-47e4-a722-19c9a6b99fac.png)

iPhone 11 14.3

**Comment by rllbe** [comment]
Please refresh repo and install update and see if it's fixed

**Comment by dimaamid** [comment]
Still the same



iTyped with my iThumbs on my iPhone. Kindly excuse tyops

**Comment by kendoss972** [comment]
after opening the weather app or i scroll,my phone freeze and restart fews seconds later,i disabled weatherdate with icleaner and everything works again,i hope a solution will be found for that and for the icon size,i'm on 12 pro max 14.2

**Comment by dimaamid** [comment]
iTyped with my iThumbs on my iPhone. Kindly excuse tyops

**Comment by rllbe** [comment]
> Still the same
> […](#)

Could you refresh repo and install the new update and see if it's fixed? 
I don't have big phones to test with. Sorry about that

**Comment by rllbe** [comment]
> after opening the weather app or i scroll,my phone freeze and restart fews seconds later,i disabled weatherdate with icleaner and everything works again

Sorry but I can't reproduce this

**Comment by dimaamid** [comment]
It’s fixed!

You are amazing! Great work. Thank you 

iTyped with my iThumbs on my iPhone. Kindly excuse tyops

**Comment by dimaamid** [comment]
Is it possible to put weather condition overlay on the weather app icon (for example, clouds moving like inside weather app). So instead of static weather icon you can have a weather conditions and temperature at the bottom of the app icon

Just an ideas. I think Asteroid used to have it

iTyped with my iThumbs on my iPhone. Kindly excuse tyops
